version: 0.2

phases:
  pre_build:
    commands:
      - echo prebuild phase
      - aws --version

  build:
    commands:
      - echo running s3 sync command
      - aws s3 sync ./ s3://${CLONE_TEMPLATE_BUCKET}/ --exclude "buildspec.yml" --exclude "buildspec-stack-update.yml" --exclude "scripts/*" --exclude "parameters/*" --exclude ".gitignore"
      - echo running stack updates
      - chmod +x ./scripts/update_stacks.sh
      - ./scripts/update_stacks.sh $STACK_ENV $Environment

artifacts:
  files:
    - "**/*"
