version: 0.2

# env:
#   variables:
#     STACK_ENV: "dev"

phases:
  pre_build:
    commands:
      - echo prebuild phase
      - aws --version

  build:
    commands:
      - echo running s3 sync command
      - aws s3 sync ./ s3://${StackBucketName}/ --exclude "buildspec.yml" --exclude ".gitignore"
      - echo running stack updates
      - chmod +x ./scripts/update_stacks.sh
      - ./scripts/update_stacks.sh

artifacts:
  files:
    - "**/*"
