version: 0.2
phases:
  pre_build:
    commands:
      - echo prebuild phase
      - aws --version

  build:
    commands:
      - echo running s3 sync command
      - aws s3 sync ./ s3://${CLONE_TEMPLATE_BUCKET}/ --exclude "buildspec.yml" --exclude "CurrentHelperRootstack.yaml" --exclude "CurrentNetworkRootstack.yaml" --exclude "CurrentInfraRootstack.yaml" --exclude ".gitignore"

     
      # Check and deploy/update helper-stack if changes are detected
      - echo checking changes for helper-stack
      - |
        if aws cloudformation describe-stacks --stack-name helper-stack-${StackENV} >/dev/null 2>&1; then
          echo "Updating helper-stack..."
          aws cloudformation create-change-set --stack-name helper-stack-${StackENV} --template-url https://test-cloudformation-template-clone-stack.s3.amazonaws.com/helper-stack/RootStack.yaml --change-set-name helper-stack-changeset --capabilities CAPABILITY_NAMED_IAM --include-nested-stacks --parameters ParameterKey=Environment,ParameterValue=${Environment} ParameterKey=ProjectName,ParameterValue=${ProjectName} ParameterKey=CodeStarConnectionID,ParameterValue=${CodeStarConnectionID} ParameterKey=StackBucketName,ParameterValue=${CLONE_TEMPLATE_BUCKET} ParameterKey=S3LogBucket,ParameterValue=${S3LogBucket}
          aws cloudformation wait change-set-create-complete --stack-name helper-stack-${StackENV} --change-set-name helper-stack-changeset
          STATUS=$(aws cloudformation describe-change-set --stack-name helper-stack-${StackENV} --change-set-name helper-stack-changeset --query 'Status' --output text)
          echo $STATUS
          STACK_NAME="helper-stack"
          sh notify-teams.sh $STACK_NAME $STATUS
          if [ "${STATUS}" == "CREATE_COMPLETE" ]; then
            notify_teams "Helper stack" "${STATUS}"
          fi

        fi

      # Check and deploy/update network-stack if changes are detected
      - echo checking changes for network-stack
      - |
        if aws cloudformation describe-stacks --stack-name network-stack-${StackENV} >/dev/null 2>&1; then
          echo "Updating network-stack..."
          aws cloudformation create-change-set --stack-name network-stack-${StackENV} --template-url https://test-cloudformation-template-clone-stack.s3.amazonaws.com/network-stack/RootStack.yaml --change-set-name network-stack-changeset --capabilities CAPABILITY_NAMED_IAM --include-nested-stacks --parameters ParameterKey=Environment,ParameterValue=${Environment} ParameterKey=ProjectName,ParameterValue=${ProjectName} ParameterKey=StackBucketName,ParameterValue=${CLONE_TEMPLATE_BUCKET}
          aws cloudformation wait change-set-create-complete --stack-name network-stack-${StackENV} --change-set-name network-stack-changeset
          STATUS=$(aws cloudformation describe-change-set --stack-name network-stack-${StackENV} --change-set-name network-stack-changeset --query 'Status' --output text)
          echo $STATUS
          STACK_NAME="network-stack"
          sh notify-teams.sh $STACK_NAME $STATUS
          if [ "${STATUS}" == "CREATE_COMPLETE" ]; then
            notify_teams "Network stack" "${STATUS}"
          fi

        fi

      # Check and deploy/update infra-stack if changes are detected
      - echo checking changes for infra-stack
      - |
        if aws cloudformation describe-stacks --stack-name infra-stack-${StackENV} >/dev/null 2>&1; then
          echo "Updating infra-stack..."
          aws cloudformation create-change-set --stack-name infra-stack-${StackENV} --template-url https://test-cloudformation-template-clone-stack.s3.amazonaws.com/infra-stack/RootStack.yaml --change-set-name infra-stack-changeset --capabilities CAPABILITY_NAMED_IAM --include-nested-stacks --parameters ParameterKey=Environment,ParameterValue=${Environment} ParameterKey=ProjectName,ParameterValue=${ProjectName} ParameterKey=CodeStarConnectionID,ParameterValue=${CodeStarConnectionID} ParameterKey=StackBucketName,ParameterValue=${CLONE_TEMPLATE_BUCKET} ParameterKey=SSLCertificateID,ParameterValue=${SSLCertificateID}
          aws cloudformation wait change-set-create-complete --stack-name infra-stack-${StackENV} --change-set-name infra-stack-changeset
          STATUS=$(aws cloudformation describe-change-set --stack-name infra-stack-${StackENV} --change-set-name infra-stack-changeset --query 'Status' --output text)
          echo $STATUS
          STACK_NAME="infra-stack"
          sh notify-teams.sh $STACK_NAME $STATUS
          if [ "${STATUS}" == "CREATE_COMPLETE" ]; then
            notify_teams "Infra stack" "${STATUS}"
          fi
          
        fi

artifacts:
  files:
    - "**/*" 
