version: 0.2
phases:
  build:
    commands:
      - echo "Checking and executing change set for helper-stack"
      - |
        CHANGE_SET_STATUS=$(aws cloudformation describe-change-set --stack-name helper-stack-${StackENV} --change-set-name helper-stack-changeset --query 'Status' --output text)
        if [ "$CHANGE_SET_STATUS" = "CREATE_COMPLETE" ]; then
          aws cloudformation execute-change-set --stack-name helper-stack-${StackENV} --change-set-name helper-stack-changeset
          aws cloudformation wait stack-update-complete --stack-name helper-stack-${StackENV}
        else
          echo "No changes detected for helper-stack or change set creation failed."
          aws cloudformation delete-change-set --stack-name helper-stack-${StackENV} --change-set-name helper-stack-changeset
        fi

      - echo "Checking and executing change set for network-stack"
      - |
        CHANGE_SET_STATUS=$(aws cloudformation describe-change-set --stack-name network-stack-${StackENV} --change-set-name network-stack-changeset --query 'Status' --output text)
        if [ "$CHANGE_SET_STATUS" = "CREATE_COMPLETE" ]; then
          aws cloudformation execute-change-set --stack-name network-stack-${StackENV} --change-set-name network-stack-changeset
          aws cloudformation wait stack-update-complete --stack-name network-stack-${StackENV}
        else
          echo "No changes detected for network-stack or change set creation failed."
          aws cloudformation delete-change-set --stack-name network-stack-${StackENV} --change-set-name network-stack-changeset
        fi

      - echo "Checking and executing change set for infra-stack"
      - |
        CHANGE_SET_STATUS=$(aws cloudformation describe-change-set --stack-name infra-stack-${StackENV} --change-set-name infra-stack-changeset --query 'Status' --output text)
        if [ "$CHANGE_SET_STATUS" = "CREATE_COMPLETE" ]; then
          aws cloudformation execute-change-set --stack-name infra-stack-${StackENV} --change-set-name infra-stack-changeset
          aws cloudformation wait stack-update-complete --stack-name infra-stack-${StackENV}
        else
          echo "No changes detected for infra-stack or change set creation failed."
          aws cloudformation delete-change-set --stack-name infra-stack-${StackENV} --change-set-name infra-stack-changeset
        fi

artifacts:
  files:
    - "**/*"
