version: 0.2

env:
  variables:
    AWS_REGION: us-west-2

phases:
  pre_build:
    commands:
      - echo prebuild phase
      - aws --version

  build:
    commands:
      - echo getting existing helper-stack template
      - aws cloudformation get-template --stack-name helper-stack-${CURRENT_STACK_ENV} --output json | jq -rc '.TemplateBody' > CurrentHelperRootstack.yaml
      - cat CurrentHelperRootstack.yaml
      - echo running aws cloudformation command to deploy helper-stack
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./CurrentHelperRootstack.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback --parameter-overrides "Environment"="${Environment}" "ProjectName=${ProjectName}" "CodeStarConnectionID=${CodeStarConnectionID}" "StackBucketName=${StackBucketName}" "S3LogBucket=${S3LogBucket}" --stack-name helper-stack-${StackENV}
      - echo helper-stack-${StackENV} deploy completed

      - echo getting existing network-stack template
      - aws cloudformation get-template --stack-name network-stack-${CURRENT_STACK_ENV} --output json | jq -rc '.TemplateBody' > CurrentNetworkRootstack.yaml
      - cat CurrentNetworkRootstack.yaml
      - echo running aws cloudformation command to deploy network-stack
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./CurrentNetworkRootstack.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback --parameter-overrides "Environment"="${Environment}" "ProjectName=${ProjectName}" "CodeStarConnectionID=${CodeStarConnectionID}" "SSLCertificateID=${SSLCertificateID}" --stack-name network-stack-${StackENV}
      - echo network-stack-${StackENV} deploy completed

      - echo getting existing infra-stack template
      - aws cloudformation get-template --stack-name infra-stack-${CURRENT_STACK_ENV} --output json | jq -rc '.TemplateBody' > CurrentInfraRootstack.yaml
      - cat CurrentInfraRootstack.yaml
      - echo running aws cloudformation command to deploy infra-stack
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./CurrentInfraRootstack.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback --parameter-overrides "Environment"="${Environment}" "ProjectName=${ProjectName}" "CodeStarConnectionID=${CodeStarConnectionID}" "SSLCertificateID=${SSLCertificateID}" --stack-name infra-stack-${StackENV}
      - echo infra-stack-${StackENV} deploy completed

      # - echo running s3 sync command
      # - aws s3 sync ./ s3://${CLONE_TEMPLATE_BUCKET}/ --exclude "buildspec-stack-update.yml" --exclude "buildspec.yml" --exclude "CurrentHelperRootstack.yaml" --exclude "CurrentNetworkRootstack.yaml" --exclude "CurrentInfraRootstack.yaml" --exclude ".gitignore"

artifacts:
  files:
    - "**/*"
