version: 0.2

env:
  variables:
    VPCId: "vpc-0d6dbbb56ffdd43f9"
    # PublicSubnets: "subnet-0bc9e2992de3412ae,subnet-0a2ee0382e3fffdea,subnet-07d88f457c3d22490,subnet-02f6f269c97e21a69,subnet-0b09996022939ca89,subnet-09913ab8e8aa50d3f"
    # PrivateSubnets: "subnet-0bf8512f3dc77c79b,subnet-010780120c4aa74c6,subnet-0a211aafd0e1af03b,subnet-067999a6e63c7abe8,subnet-0b7f741ecc9c96c4e,subnet-0e92d3f901abbe4d2"
    # HTTPSListener1: "arn:aws:elasticloadbalancing:us-east-1:484537496937:listener/app/saran-dev-alb/c91cf37143bcddb9/6846a10a435505fa"
    # HTTPSListener2: "arn:aws:elasticloadbalancing:us-east-1:484537496937:listener/app/saran-dev-alb/c91cf37143bcddb9/786465df81c6d263"
    # SecurityGroup: "sg-03a5216036e64eaa4"

phases:
  pre_build:
    commands:
      - echo prebuild phase
      - aws --version

  build:
    commands:
      - echo running s3 sync command
      # - aws s3 sync ./ s3://${CLONE_TEMPLATE_BUCKET}/ --exclude "buildspec.yml" --exclude ".gitignore"
      - aws s3 sync ./ s3://${CLONE_TEMPLATE_BUCKET}/ --exclude "buildspec.yml" --exclude "buildspec-stack-update.yml" --exclude "scripts/*" --exclude "parameters/*" --exclude ".gitignore"
      - echo running stack updates
      - chmod +x ./scripts/update_stacks.sh
      - ./scripts/update_stacks.sh

artifacts:
  files:
    - "**/*"
