version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building the project...
      - chmod +x execute_change_sets.sh
      - ./execute_change_sets.sh ${StackENV}
