version: 0.2
phases:
  pre_build:
    commands:
      - echo prebuild phase
      - aws --version
  build:
    commands:
      - echo running aws cloudformation command to deploy helper-stack
      - aws cloudformation create-change-set --stack-name helper-stack-${StackENV} --template-body file://helper-stack/RootStack.yaml --change-set-name helper-stack-changeset --capabilities CAPABILITY_NAMED_IAM --parameters ParameterKey=Environment,ParameterValue=${Environment} ParameterKey=ProjectName,ParameterValue=${ProjectName} ParameterKey=CodeStarConnectionID,ParameterValue=${CodeStarConnectionID} ParameterKey=StackBucketName,ParameterValue=${CLONE_TEMPLATE_BUCKET} ParameterKey=S3LogBucket,ParameterValue=${S3LogBucket} ParameterKey=SSLCertificateID,ParameterValue=${SSLCertificateID}
      - aws cloudformation wait change-set-create-complete --stack-name helper-stack-${StackENV} --change-set-name helper-stack-changeset
      # - aws cloudformation execute-change-set --stack-name helper-stack-${StackENV} --change-set-name helper-stack-changeset --no-execute-unless
      - echo helper-stack deploy completed

      - echo running aws cloudformation command to deploy network-stack
      - aws cloudformation create-change-set --stack-name network-stack-${StackENV} --template-body file://network-stack/RootStack.yaml --change-set-name network-stack-changeset --capabilities CAPABILITY_NAMED_IAM --parameters ParameterKey=Environment,ParameterValue=${Environment} ParameterKey=ProjectName,ParameterValue=${ProjectName} ParameterKey=CodeStarConnectionID,ParameterValue=${CodeStarConnectionID} ParameterKey=StackBucketName,ParameterValue=${CLONE_TEMPLATE_BUCKET} ParameterKey=SSLCertificateID,ParameterValue=${SSLCertificateID}
      - aws cloudformation wait change-set-create-complete --stack-name network-stack-${StackENV} --change-set-name network-stack-changeset
      # - aws cloudformation execute-change-set --stack-name network-stack-${StackENV} --change-set-name network-stack-changeset --no-execute-unless
      - echo network-stack deploy completed

      - echo running aws cloudformation command to deploy infra-stack
      - aws cloudformation create-change-set --stack-name infra-stack-${StackENV} --template-body file://infra-stack/RootStack.yaml --change-set-name infra-stack-changeset --capabilities CAPABILITY_NAMED_IAM --parameters ParameterKey=Environment,ParameterValue=${Environment} ParameterKey=ProjectName,ParameterValue=${ProjectName} ParameterKey=CodeStarConnectionID,ParameterValue=${CodeStarConnectionID} ParameterKey=StackBucketName,ParameterValue=${CLONE_TEMPLATE_BUCKET} ParameterKey=SSLCertificateID,ParameterValue=${SSLCertificateID}
      - aws cloudformation wait change-set-create-complete --stack-name infra-stack-${StackENV} --change-set-name infra-stack-changeset
      # - aws cloudformation execute-change-set --stack-name infra-stack-${StackENV} --change-set-name infra-stack-changeset --no-execute-unless
      - echo infra-stack deploy completed

      - echo running s3 sync command
      - aws s3 sync ./ s3://${CURRENT_TEMPLATE_BUCKET}/ --exclude "buildspec-stack-update.yml" --exclude "buildspec.yml" --exclude ".*"
artifacts:
  files:
    - "**/*"
