AWSTemplateFormatVersion: '2010-09-09'
Description: This is a network stack which deploys VPC and SecurityGroup.
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - prod
      - dev
      - stage
      - clone
  ProjectName:
    Type: String
  StackBucketName:
    Type: String
  VPCId:
    Type: String
    Description: Required if the environment is a staging
    Default: "DummyValue"

Conditions:
  Staging: !Equals [!Ref Environment, stage]
  Development: !Equals [!Ref Environment, dev]
  Production: !Equals [!Ref Environment, prod]
  Clone: !Equals [!Ref Environment, clone]
  CreateResource: !Or [!Equals [ !Ref Environment, dev ], !Equals [ !Ref Environment, prod ], !Equals [ !Ref Environment, clone ]]

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResource
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/network-stack/VPC.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/network-stack/SecurityGroup.yaml
      Parameters:
        VPC: !If
          - Staging
          - !Ref VPCId
          - !GetAtt VPC.Outputs.VPC 
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

