AWSTemplateFormatVersion: '2010-09-09'
Description: This is a network stack which deploys VPC and SecurityGroup.
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - production
      - development
      - staging
      - clone
  ProjectName:
    Type: String
  StackBucketName:
    Type: String    

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/network-stack/VPC.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPC
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/network-stack/SecurityGroup.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPC
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

