AWSTemplateFormatVersion: '2010-09-09'
Description: This is a helper stack which creates resources like S3, SNS, IAM, ECR.
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - production
      - development
      - staging
      - clone
  ProjectName:
    Type: String
  StackBucketName:
    Type: String
  CodeStarConnectionID:
    Type: String
  S3LogBucket:
    Type: String

Resources:
  S3:
    Description: This is a S3 stack which creates buckets.
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/helper-stack/S3.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

  IAM:
    Description: This is a IAM stack which creates neccessary roles and permissions.
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/helper-stack/IAM.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        S3LogBucket: !Ref S3LogBucket

  SNS:
    Description: This is a SNS stack which creates notification.
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/helper-stack/SNS.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

  ECR:
    Description: Docker Image repository
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/helper-stack/ECR.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

  SAMPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${StackBucketName}/helper-stack/SAMPipeline.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        CodeStarConnectionID: !Ref CodeStarConnectionID
