AWSTemplateFormatVersion: "2010-09-09"
Description: This is a S3 stack which creates buckets.
Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String

Conditions:
  ProdEnv: !Equals [ !Ref Environment, prod ]
  DevEnv: !Equals [ !Ref Environment, dev ]
  StageEnv: !Equals [ !Ref Environment, stage ]
  CloneEnv: !Equals [ !Ref Environment, clone ]

Resources:
  DeploymentArtifactS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ProjectName}-combined-pipeline-artifact-${Environment}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        -
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
          BucketKeyEnabled: true
      VersioningConfiguration:
        Status: "Enabled"
      OwnershipControls:
        Rules:
        -
          ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  
  DeploymentArtifactS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref DeploymentArtifactS3Bucket
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
        - Sid: AllowSSLRequestsOnly
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource:
          - !Join ['', [!GetAtt DeploymentArtifactS3Bucket.Arn, '/*']]
          - !GetAtt DeploymentArtifactS3Bucket.Arn
          Condition:
            Bool:
              aws:SecureTransport: 'false'
  
  PipelineArtifactS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "codepipeline-${AWS::Region}-artifacts-${ProjectName}-${Environment}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        -
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
          BucketKeyEnabled: true
      OwnershipControls:
        Rules:
        -
          ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  
  PipelineArtifactS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref PipelineArtifactS3Bucket
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
        - Sid: AllowSSLRequestsOnly
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource:
          - !Join ['', [!GetAtt PipelineArtifactS3Bucket.Arn, '/*']]
          - !GetAtt PipelineArtifactS3Bucket.Arn
          Condition:
            Bool:
              aws:SecureTransport: 'false'
  
  AssetsS3bucket:
    Type: AWS::S3::Bucket
    Condition: DevEnv
    Properties:
      BucketName: !Sub "${ProjectName}-assets"
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
            - "Authorization"
          AllowedMethods:
            - "GET"
          AllowedOrigins: 
            - !Sub "https://assets.${ProjectName}.com"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}

  TestAssetsS3bucket:
    Type: AWS::S3::Bucket
    Condition: CloneEnv
    Properties:
      BucketName: !Sub "${ProjectName}-${Environment}-assets"
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
            - "Authorization"
          AllowedMethods:
            - "GET"
          AllowedOrigins: 
            - !Sub "https://assets-clone.${ProjectName}.com"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}

  #Custom_resource_lambda_fuction_has_to_be_added_manually&lambda_function_name_should_be_same_in_all_accound
  DeploymentArtifactS3BucketDeletion:
    Type: Custom::DeploymentArtifactS3BucketDeletion
    Properties:
      bucket_name: !Ref DeploymentArtifactS3Bucket
      ServiceToken: !Sub "arn:aws:lambda:us-east-1:${AWS::AccountId}:function:S3bucketDelete"

  #Custom_resource_lambda_fuction_has_to_be_added_manually&lambda_function_name_should_be_same_in_all_accound
  AssetsS3bucketS3BucketDeletion:
    Type: Custom::AssetsS3bucketDeletion
    Condition: DevEnv
    Properties:
      bucket_name: !Ref AssetsS3bucket
      ServiceToken: !Sub "arn:aws:lambda:us-east-1:${AWS::AccountId}:function:S3bucketDelete"
  
  #Custom_resource_lambda_fuction_has_to_be_added_manually&lambda_function_name_should_be_same_in_all_accound
  PipelineArtifactS3BucketDeletion:
    Type: Custom::PipelineArtifactS3BucketDeletion
    Properties:
      bucket_name: !Ref PipelineArtifactS3Bucket
      ServiceToken: !Sub "arn:aws:lambda:us-east-1:${AWS::AccountId}:function:S3bucketDelete"

  #Custom_resource_lambda_fuction_has_to_be_added_manually&lambda_function_name_should_be_same_in_all_accound
  TestAssetsS3bucketS3BucketDeletion:
    Type: Custom::TestAssetsS3bucketDeletion
    Condition: CloneEnv
    Properties:
      bucket_name: !Ref TestAssetsS3bucket
      ServiceToken: !Sub "arn:aws:lambda:us-east-1:${AWS::AccountId}:function:S3bucketDelete"