AWSTemplateFormatVersion: '2010-09-09'
Description: This stack is for creating alb.
Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  VPC:
    Description: VPC
    Type: String
  LoadbalancerSecurityGroup:
    Description: LoadbalancerSecurityGroup
    Type: String
  SSLCertificateID:
    Type: String
  PublicSubnets:
    Description: PublicSubnets
    Type: CommaDelimitedList

Resources:
  Loadbalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-alb
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref LoadbalancerSecurityGroup
      Type: application

  TargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-TG-1
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /healthy
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  TargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-TG-2
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /healthy
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Loadbalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Host: '#{host}'
            Path: '/#{path}'
            Query: '#{query}'
            Port: 443
            Protocol: HTTPS
            StatusCode: HTTP_301

  HTTPSListener1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Sub "arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${SSLCertificateID}"
      LoadBalancerArn: !Ref Loadbalancer
      Port: 443
      Protocol: HTTPS
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup2
    DependsOn: TargetGroup1

  HTTPSListener2:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Sub "arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${SSLCertificateID}"
      LoadBalancerArn: !Ref Loadbalancer
      Port: 9443
      Protocol: HTTPS
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup2
    DependsOn: TargetGroup2

Outputs:
  Loadbalancer:
    Value: !GetAtt Loadbalancer.DNSName
  TargetGroup1:
    Value: !Ref TargetGroup1
  TargetGroup2:
    Value: !Ref TargetGroup2
  TargetGroup1Name:
    Value: !GetAtt TargetGroup1.TargetGroupName
  TargetGroup2Name:
    Value: !GetAtt TargetGroup2.TargetGroupName
  ProdListener:
    Value: !Ref HTTPSListener1
  TestListener:
    Value: !Ref HTTPSListener2




